services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: tanquoc
      MONGO_INITDB_ROOT_PASSWORD: 7324*Tan
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      mongodb-data-container:
    